baseURL = "https://jclegras.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Jean-Charles Legras' blog"
theme = "anatole"
summarylength = 10
enableEmoji = false

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "I'm Jean-Charles Legras"
author = "Jean-Charles Legras"
description = "Call me JC"
profilePicture = "profile.webp"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["posts"]
contentratio = 0.7

## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/jean-charles-legras-708b39a4/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jclegras"

[[params.socialIcons]]
icon = "fa-solid fa-envelope"
title = "e-mail"
url = "mailto:jeancharles.legras@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"